FROM python:3.9.7-slim

ENV PYTHONBUFFERED=1

RUN apt-get update && apt-get install -y \
    ffmpeg \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./server/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY server/river_modified/pa.py \
    /usr/local/lib/python3.9/site-packages/river/linear_model/pa.py

COPY server/ /app/server/

RUN echo 'export PS1="\u@$(hostname -s):\w\$ "' >> /root/.bashrc